virtualenv/djangoEnv/Multi_Apps/Multi_Apps/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.multiapp.urls')),
    url(r'^login_reg/', include('apps.login_reg.urls', namespace='login_reg')),
    url(r'^courses/', include('apps.courses.urls', namespace='courses')),
]

virtualenv/djangoEnv/Multi_Apps/apps/courses/urls.py
from django.conf.urls import url
from . import views
#from django.contrib import admin

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^add$', views.add, name = 'add'),
    url(r'^delete/(?P<id>\d+)$', views.delete),
    url(r'^destroy/(?P<id>\d+)$', views.destroy),
    url(r'^users_courses$', views.users_courses, name = 'u_c'),
    url(r'^makeaccount$', views.makeaccount, name = 'makeaccount')
]

virtualenv/djangoEnv/Multi_Apps/apps/courses/models.py
from __future__ import unicode_literals
from django.db import models
from ..login_reg.models import Users

class UserManager(models.Manager):
    def user(self):
        users = Users.usermanager.all()
        return(True, users)

    def add_user_to_course(self, data):
        course = self.get(id=data['course'])
        user = Users.usermanager.get(id=data['user'])
        course.account.add(user)
        course.save()

# Create your models here.
class Courses(models.Model):
    name = models.CharField(max_length=100, null=True)
    description = models.TextField(max_length=1000, null=True)
    account = models.ManyToManyField(Users, related_name = "userstocourses")
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    usermanager = UserManager()

virtualenv/djangoEnv/Multi_Apps/apps/courses/views.py
from django.shortcuts import render, HttpResponse, redirect
from . import models
from models import Courses
from django.core.urlresolvers import reverse
from django.db.models import Count

def index(request):

    courses = models.Courses.usermanager.all()
    context = {
        'courses':courses
    }
    return render(request, 'courses/index.html', context)

def add(request):
    n = Courses(name=request.POST['name'], description=request.POST['description'])
    n.save()
    return redirect(reverse('courses:index'))

def delete(request, id):
    courses = models.Courses.usermanager.get(id=id)
    context = {
        'name':courses.name,
        'description':courses.description,
        'id':courses.id
    }
    return render(request, 'courses/destroy.html', context)

def destroy(request, id):
    d = models.Courses.usermanager.get(id=id)
    d.delete()
    return redirect(reverse('courses:u_c'))

def users_courses(request):
    courses = models.Courses.usermanager.annotate(students=Count('account'))
    users = models.Courses.usermanager.user()
    print courses
    print users
    context = {
        'courses':courses,
        'users':users[1]
    }
    return render(request, 'courses/u_c.html', context)

def makeaccount(request):
    Courses.usermanager.add_user_to_course(request.POST)
    return redirect(reverse('courses:u_c'))

virtualenv/djangoEnv/Multi_Apps/apps/courses/templates/courses/destroy.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Delete page</title>
    </head>
    <body>
        <h4>Are you sure you want to delete the following course?</h4>
        <p>
            Name: {{name}}
            description: {{description}}
        </p>
        <form class="" action="/" method="post">
            {% csrf_token %}
            <input type="submit" name="no" value="No">
        </form>
        <form class="" action="/courses/destroy/{{id}}" method="post">
            {% csrf_token %}
            <input type="submit" name="delete" value="Yes! I want to delete this">
        </form>
    </body>
</html>

virtualenv/djangoEnv/Multi_Apps/apps/courses/templates/courses/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Courses list</title>
    </head>
    <body>
        <div class="">
            <h3>Add a new course</h3>
            <form id="profile" action="/courses/add" method="post">
                {% csrf_token %}
                Name:
                <input type="text" name="name" value="">
                Description:
                <textarea name="description" rows="8" cols="80"></textarea>
                <input type="submit" name="" value="Add">
            </form>
        </div>
        <div class="">
            <table>
                <tr>
                    <th>Course Name</th>
                    <th>Description</th>
                    <th>Date Added</th>
                    <th>Actions</th>
                </tr>
                {% for course in courses %}
                <tr>
                    <td>{{course.name}}</td>
                    <td>{{course.description}}</td>
                    <td>{{course.created_at}}</td>
                    <td>
                        <form class="" action="/delete/{{course.id}}" method="post">
                        {% csrf_token %}
                        <input type="submit" name="remove" value="remove">
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <form class="" action="/" method="post">
            {% csrf_token %}
            <input type="submit" name="" value="Return Home">
        </form>
    </body>
</html>

virtualenv/djangoEnv/Multi_Apps/apps/courses/templates/courses/u_c.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Users_Courses</title>
    </head>
    <body>
        <form class="" action="{% url 'courses:makeaccount' %}" method="post">
            {% csrf_token %}
            <select class="" name="user">
                {% for user in users %}
                <option value="{{user.id}}">{{user.email}}</option>
                {% endfor %}
            </select>
            <select class="" name="course">
                {% for course in courses %}
                <option value="{{course.id}}">{{course.name}}</option>
                {% endfor %}
            </select>
            <input type="submit" name="" value="Add User To Course">
        </form>
        <div class="">
            <table>
                <tr>
                    <th>Course</th>
                    <th>Title</th>
                    <th>Number of Users</th>
                </tr>
                {% for course in courses %}
                <tr>
                    <td>{{course.id}}</td>
                    <td>{{course.name}}</td>
                    <td>{{course.students}}</td>
                    <td>
                        <form class="" action="/courses/delete/{{course.id}}" method="post">
                        {% csrf_token %}
                        <input type="submit" name="remove" value="remove">
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </table>
            <form class="" action="{% url 'courses:index' %}" method="post">
                {% csrf_token %}
                <input type="submit" name="return" value="Return Home">
            </form>
    </body>
</html>